// Package firewall provides a compliance plugin for firewall-specific security checks.
package firewall

import "github.com/EvilBit-Labs/opnDossier/internal/compliance"

// newControlDefinitions returns the control definitions for FIREWALL-009 through -061.
// These are appended to the original 8 controls in the NewPlugin constructor.
//
//nolint:funlen // 53 control definitions are inherently verbose
func newControlDefinitions() []compliance.Control {
	return []compliance.Control{
		// Management Plane controls (FIREWALL-009 through -021)
		{
			ID:          "FIREWALL-009",
			Title:       "Non-Default Web GUI Port",
			Description: "Web GUI should use a non-default port to reduce automated scanning exposure",
			Category:    "Management Access",
			Severity:    "low",
			Rationale:   "Using a non-default port reduces exposure to automated port scanners targeting standard ports",
			Remediation: "Change the web GUI port in System > Settings > Administration",
			Tags:        []string{"management-access", "port-security", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-010",
			Title:       "Management Interface Restriction",
			Description: "Web GUI access should be restricted to specific management interfaces",
			Category:    "Management Access",
			Severity:    "high",
			Rationale:   "Restricting management access to dedicated interfaces prevents unauthorized access from untrusted networks",
			Remediation: "Bind the web GUI to a dedicated management interface in System > Settings > Administration",
			Tags:        []string{"management-access", "interface-binding", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-011",
			Title:       "TLS Version Minimum",
			Description: "Web GUI should enforce a minimum TLS version of 1.2 or higher",
			Category:    "Management Access",
			Severity:    "high",
			Rationale:   "Older TLS versions (1.0, 1.1) have known vulnerabilities that can be exploited",
			Remediation: "Set minimum TLS version to 1.2 in System > Settings > Administration",
			Tags:        []string{"management-access", "tls", "encryption", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-012",
			Title:       "Anti-Lockout Rule Awareness",
			Description: "Anti-lockout rule status should be documented and intentional",
			Category:    "Management Access",
			Severity:    "low",
			Rationale:   "The anti-lockout rule bypasses normal firewall policy and should be a conscious decision",
			Remediation: "Review anti-lockout rule status in System > Settings > Administration",
			Tags:        []string{"management-access", "anti-lockout", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-013",
			Title:       "Session Timeout",
			Description: "Management sessions should have a timeout configured",
			Category:    "Management Access",
			Severity:    "medium",
			Rationale:   "Session timeouts prevent unauthorized access from abandoned sessions",
			Remediation: "Configure session timeout in System > Settings > Administration",
			Tags:        []string{"management-access", "session-timeout", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-014",
			Title:       "Console Menu Protection",
			Description: "Serial/VGA console menu should be disabled to prevent unauthorized physical access",
			Category:    "Management Access",
			Severity:    "medium",
			Rationale:   "Disabling the console menu prevents physical access from granting immediate shell access",
			Remediation: "Disable console menu in System > Settings > Administration",
			Tags:        []string{"management-access", "console-security", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-015",
			Title:       "Login Protection / Brute Force",
			Description: "Login brute-force protection should be enabled",
			Category:    "Management Access",
			Severity:    "medium",
			Rationale:   "Brute-force protection limits the rate of login attempts to prevent credential guessing",
			Remediation: "Enable login protection in System > Settings > Administration",
			Tags:        []string{"management-access", "brute-force", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-016",
			Title:       "Default Credential Reset",
			Description: "Default administrative accounts should be disabled or renamed",
			Category:    "Authentication",
			Severity:    "critical",
			Rationale:   "Default credentials are publicly known and are the first targets of automated attacks",
			Remediation: "Disable or rename default admin/root accounts and create named individual accounts",
			Tags:        []string{"authentication", "default-credentials", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-017",
			Title:       "Unique Administrator Accounts",
			Description: "Each administrator should have a unique named account instead of sharing a generic admin account",
			Category:    "Authentication",
			Severity:    "medium",
			Rationale:   "Shared accounts prevent attribution of administrative actions in audit logs",
			Remediation: "Create individual named accounts for each administrator and disable the generic admin account",
			Tags:        []string{"authentication", "accountability", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-018",
			Title:       "Least Privilege Access",
			Description: "Administrative access should follow the principle of least privilege",
			Category:    "Authentication",
			Severity:    "medium",
			Rationale:   "Granting page-all privileges to a user or group provides unrestricted access beyond what most roles require",
			Remediation: "Replace page-all privileges with specific page-level permissions matched to each role",
			Tags:        []string{"authentication", "least-privilege", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-019",
			Title:       "Centralized Authentication",
			Description: "Authentication should use a centralized directory (RADIUS, LDAP) for consistent access control",
			Category:    "Authentication",
			Severity:    "medium",
			Rationale:   "Centralized authentication enables consistent password policies and simplified account lifecycle management",
			Remediation: "Configure RADIUS or LDAP authentication in System > Access > Servers",
			Tags:        []string{"authentication", "centralized-auth", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-020",
			Title:       "Disabled Unused Accounts",
			Description: "Unused system accounts with default names should be disabled",
			Category:    "Authentication",
			Severity:    "medium",
			Rationale:   "Enabled system accounts with default names are attractive targets for attackers",
			Remediation: "Disable system accounts with default names (admin, root) that are no longer needed",
			Tags:        []string{"authentication", "account-hygiene", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-021",
			Title:       "Group-Based Privileges",
			Description: "Privileges should be assigned through groups rather than directly to users",
			Category:    "Authentication",
			Severity:    "low",
			Rationale:   "Group-based access control simplifies privilege management and auditing",
			Remediation: "Create groups with appropriate privileges and assign users to groups",
			Tags:        []string{"authentication", "group-privileges", "firewall-controls"},
		},
		// Rule Hygiene controls (FIREWALL-022 through -035)
		{
			ID:          "FIREWALL-022",
			Title:       "No Any-Any Pass Rules",
			Description: "No firewall pass rules should have source, destination, port, and protocol all set to any",
			Category:    "Firewall Rule Hygiene",
			Severity:    "high",
			Rationale:   "Any-any pass rules effectively disable the firewall for matching traffic",
			Remediation: "Replace any-any rules with specific source, destination, port, and protocol restrictions",
			Tags:        []string{"rule-hygiene", "overly-permissive", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-023",
			Title:       "No Any Source on WAN Inbound",
			Description: "WAN pass rules should not allow any source address",
			Category:    "Firewall Rule Hygiene",
			Severity:    "high",
			Rationale:   "Allowing any source on WAN exposes services to the entire internet without restriction",
			Remediation: "Restrict WAN inbound rules to specific source addresses or networks",
			Tags:        []string{"rule-hygiene", "wan-security", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-024",
			Title:       "Specific Port Rules",
			Description: "Pass rules should specify explicit destination ports",
			Category:    "Firewall Rule Hygiene",
			Severity:    "medium",
			Rationale:   "Rules without port restrictions allow all services through, increasing attack surface",
			Remediation: "Specify explicit destination ports on all TCP/UDP pass rules",
			Tags:        []string{"rule-hygiene", "port-specificity", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-025",
			Title:       "Rule Documentation",
			Description: "All enabled firewall rules should have a description",
			Category:    "Firewall Rule Hygiene",
			Severity:    "medium",
			Rationale:   "Rule descriptions are essential for auditability and change management",
			Remediation: "Add meaningful descriptions to all firewall rules explaining their purpose",
			Tags:        []string{"rule-hygiene", "documentation", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-026",
			Title:       "Disabled Rule Cleanup",
			Description: "Disabled firewall rules should be periodically cleaned up",
			Category:    "Firewall Rule Hygiene",
			Severity:    "info",
			Rationale:   "Excessive disabled rules indicate stale configuration that complicates auditing",
			Remediation: "Review and remove disabled rules that are no longer needed",
			Tags:        []string{"rule-hygiene", "cleanup", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-027",
			Title:       "Protocol Specification",
			Description: "Pass rules should specify an explicit protocol",
			Category:    "Firewall Rule Hygiene",
			Severity:    "medium",
			Rationale:   "Rules without protocol specification match all protocols, which is overly permissive",
			Remediation: "Specify TCP, UDP, or ICMP protocol on all pass rules",
			Tags:        []string{"rule-hygiene", "protocol-specificity", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-028",
			Title:       "Pass Rule Logging",
			Description: "Pass rules should have logging enabled for traffic visibility",
			Category:    "Firewall Rule Hygiene",
			Severity:    "medium",
			Rationale:   "Logging on pass rules provides visibility into allowed traffic for forensic analysis",
			Remediation: "Enable logging on pass rules in Firewall > Rules",
			Tags:        []string{"rule-hygiene", "logging", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-029",
			Title:       "Private Address Filtering on WAN",
			Description: "WAN interfaces should block RFC 1918 private addresses",
			Category:    "Network Segmentation",
			Severity:    "critical",
			Rationale:   "Private addresses on WAN indicate spoofing or misconfiguration and should be blocked",
			Remediation: "Enable Block private networks on WAN interfaces in Interfaces > WAN",
			Tags:        []string{"network-segmentation", "private-addresses", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-030",
			Title:       "Bogon Filtering on WAN",
			Description: "WAN interfaces should block bogon (unassigned/reserved) addresses",
			Category:    "Network Segmentation",
			Severity:    "critical",
			Rationale:   "Bogon addresses should never appear on the public internet and indicate spoofing",
			Remediation: "Enable Block bogon networks on WAN interfaces in Interfaces > WAN",
			Tags:        []string{"network-segmentation", "bogon-filtering", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-031",
			Title:       "Unused Interface Disablement",
			Description: "Unused network interfaces should be disabled",
			Category:    "Network Segmentation",
			Severity:    "low",
			Rationale:   "Enabled but unused interfaces represent unnecessary attack surface",
			Remediation: "Disable unused interfaces in Interfaces > Assignments",
			Tags:        []string{"network-segmentation", "attack-surface", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-032",
			Title:       "VLAN Segmentation",
			Description: "Network should use VLAN segmentation",
			Category:    "Network Segmentation",
			Severity:    "medium",
			Rationale:   "VLANs segment traffic to limit lateral movement and enforce security boundaries",
			Remediation: "Configure VLANs in Interfaces > Other Types > VLAN to segment the network",
			Tags:        []string{"network-segmentation", "vlans", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-033",
			Title:       "Source Route Rejection",
			Description: "IP source routing should be disabled",
			Category:    "Anti-Spoofing",
			Severity:    "high",
			Rationale:   "Source routing allows attackers to specify packet routes and bypass security controls",
			Remediation: "Set net.inet.ip.sourceroute to 0 in System > Settings > Tunables",
			Tags:        []string{"anti-spoofing", "source-routing", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-034",
			Title:       "SYN Flood Protection",
			Description: "TCP SYN cookies should be enabled to mitigate SYN flood attacks",
			Category:    "Anti-Spoofing",
			Severity:    "medium",
			Rationale:   "SYN cookies prevent SYN flood denial-of-service attacks without maintaining half-open connections",
			Remediation: "Set net.inet.tcp.syncookies to 1 in System > Settings > Tunables",
			Tags:        []string{"anti-spoofing", "syn-flood", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-035",
			Title:       "Connection State Limits",
			Description: "Firewall should enforce connection state limits to prevent resource exhaustion",
			Category:    "Anti-Spoofing",
			Severity:    "medium",
			Rationale:   "Connection state limits prevent attackers from exhausting firewall state tables",
			Remediation: "Configure maximum states in Firewall > Settings > Advanced",
			Tags:        []string{"anti-spoofing", "state-limits", "firewall-controls"},
		},
		// Encryption & Monitoring controls (FIREWALL-036 through -053)
		{
			ID:          "FIREWALL-036",
			Title:       "Valid Web GUI Certificate",
			Description: "Web GUI should have a valid TLS certificate configured",
			Category:    "Encryption",
			Severity:    "medium",
			Rationale:   "A valid certificate ensures encrypted management traffic and prevents MITM attacks",
			Remediation: "Configure a valid TLS certificate in System > Trust > Certificates and assign it to the web GUI",
			Tags:        []string{"encryption", "certificates", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-037",
			Title:       "Certificate Expiration",
			Description: "TLS certificates should not be expired or near expiration",
			Category:    "Encryption",
			Severity:    "medium",
			Rationale:   "Expired certificates cause service disruptions and security warnings",
			Remediation: "Renew certificates before expiration in System > Trust > Certificates",
			Tags:        []string{"encryption", "certificate-expiry", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-038",
			Title:       "Strong Key Lengths",
			Description: "TLS certificates should use strong key lengths (2048-bit RSA minimum or ECDSA)",
			Category:    "Encryption",
			Severity:    "medium",
			Rationale:   "Short key lengths are vulnerable to brute-force attacks and factorization",
			Remediation: "Generate new certificates with 2048-bit RSA or ECDSA keys",
			Tags:        []string{"encryption", "key-length", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-039",
			Title:       "Remote Syslog Configured",
			Description: "Remote syslog forwarding should be configured for centralized logging",
			Category:    "Logging",
			Severity:    "high",
			Rationale:   "Centralized logging ensures log integrity and enables correlation across devices",
			Remediation: "Configure remote syslog in System > Settings > Logging / targets",
			Tags:        []string{"logging", "remote-syslog", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-040",
			Title:       "Authentication Event Logging",
			Description: "Authentication events should be forwarded to the remote syslog server",
			Category:    "Logging",
			Severity:    "medium",
			Rationale:   "Authentication logs are essential for detecting unauthorized access attempts",
			Remediation: "Enable authentication logging in System > Settings > Logging / targets",
			Tags:        []string{"logging", "auth-logging", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-041",
			Title:       "Firewall Filter Logging",
			Description: "Firewall filter events should be forwarded to the remote syslog server",
			Category:    "Logging",
			Severity:    "medium",
			Rationale:   "Firewall filter logs provide visibility into blocked and allowed traffic",
			Remediation: "Enable filter logging in System > Settings > Logging / targets",
			Tags:        []string{"logging", "filter-logging", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-042",
			Title:       "Log Retention Configuration",
			Description: "Log retention settings should be configured",
			Category:    "Logging",
			Severity:    "info",
			Rationale:   "Proper log retention ensures sufficient history for incident investigation",
			Remediation: "Configure log file size and rotation in System > Settings > Logging",
			Tags:        []string{"logging", "log-retention", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-043",
			Title:       "NTP Configuration",
			Description: "At least two NTP servers should be configured for reliable time synchronization",
			Category:    "Time Synchronization",
			Severity:    "medium",
			Rationale:   "Multiple NTP servers enable detection of faulty time sources and ensure accuracy",
			Remediation: "Configure at least two NTP servers in System > Settings > General",
			Tags:        []string{"time-sync", "ntp", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-044",
			Title:       "Timezone Configuration",
			Description: "System timezone should be explicitly configured",
			Category:    "Time Synchronization",
			Severity:    "info",
			Rationale:   "Correct timezone ensures log timestamps are meaningful for incident response",
			Remediation: "Set timezone in System > Settings > General",
			Tags:        []string{"time-sync", "timezone", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-045",
			Title:       "SNMP Disabled if Unused",
			Description: "SNMP should be disabled if not actively required",
			Category:    "SNMP Security",
			Severity:    "medium",
			Rationale:   "SNMP exposes device information and can be exploited for reconnaissance",
			Remediation: "Remove SNMP community string if SNMP monitoring is not required",
			Tags:        []string{"snmp-security", "attack-surface", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-046",
			Title:       "No Default Community Strings",
			Description: "SNMP should not use default community strings (public, private)",
			Category:    "SNMP Security",
			Severity:    "high",
			Rationale:   "Default community strings are well-known and provide no access control",
			Remediation: "Change SNMP community string to a unique, complex value in Services > SNMP",
			Tags:        []string{"snmp-security", "default-credentials", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-047",
			Title:       "Strong VPN Encryption",
			Description: "IPsec VPN tunnels should use strong encryption algorithms",
			Category:    "VPN Configuration",
			Severity:    "high",
			Rationale:   "Weak encryption (DES, 3DES, Blowfish) can be broken and exposes VPN traffic",
			Remediation: "Configure AES-256-GCM or AES-128-GCM encryption for IPsec Phase 2 tunnels",
			Tags:        []string{"vpn-config", "encryption", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-048",
			Title:       "Strong VPN Integrity",
			Description: "IPsec VPN tunnels should use strong hash algorithms for integrity",
			Category:    "VPN Configuration",
			Severity:    "high",
			Rationale:   "Weak hash algorithms (MD5, SHA-1) are vulnerable to collision attacks",
			Remediation: "Configure SHA-256 or stronger hash algorithms for IPsec Phase 2 tunnels",
			Tags:        []string{"vpn-config", "integrity", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-049",
			Title:       "Perfect Forward Secrecy",
			Description: "IPsec VPN tunnels should use Perfect Forward Secrecy",
			Category:    "VPN Configuration",
			Severity:    "high",
			Rationale:   "PFS ensures that compromise of a long-term key does not compromise past session keys",
			Remediation: "Enable PFS with a DH group on IPsec Phase 2 tunnels",
			Tags:        []string{"vpn-config", "pfs", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-050",
			Title:       "VPN Key Lifetime",
			Description: "IPsec VPN tunnels should have a configured key lifetime",
			Category:    "VPN Configuration",
			Severity:    "medium",
			Rationale:   "Unlimited key lifetimes allow compromised keys to remain in use indefinitely",
			Remediation: "Configure an appropriate key lifetime for IPsec Phase 2 tunnels",
			Tags:        []string{"vpn-config", "key-lifetime", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-051",
			Title:       "No IKEv1 Aggressive Mode",
			Description: "IPsec tunnels should not use IKEv1 aggressive mode",
			Category:    "VPN Configuration",
			Severity:    "high",
			Rationale:   "IKEv1 aggressive mode exposes pre-shared key hashes to offline brute-force attacks",
			Remediation: "Switch IKEv1 tunnels from aggressive mode to main mode, or migrate to IKEv2",
			Tags:        []string{"vpn-config", "ikev1", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-052",
			Title:       "IKEv2 Preferred",
			Description: "IPsec tunnels should use IKEv2 instead of IKEv1",
			Category:    "VPN Configuration",
			Severity:    "medium",
			Rationale:   "IKEv2 provides improved security, reduced complexity, and built-in NAT traversal",
			Remediation: "Migrate IPsec tunnels from IKEv1 to IKEv2 where peer support allows",
			Tags:        []string{"vpn-config", "ikev2", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-053",
			Title:       "Dead Peer Detection",
			Description: "IPsec tunnels should have Dead Peer Detection configured",
			Category:    "VPN Configuration",
			Severity:    "medium",
			Rationale:   "DPD detects unresponsive peers and triggers renegotiation for tunnel availability",
			Remediation: "Configure DPD delay and maximum failures on IPsec Phase 1 tunnels",
			Tags:        []string{"vpn-config", "dpd", "firewall-controls"},
		},
		// Services controls (FIREWALL-054 through -061)
		{
			ID:          "FIREWALL-054",
			Title:       "Documented Port Forwards",
			Description: "All inbound NAT (port-forward) rules should have descriptions",
			Category:    "NAT Security",
			Severity:    "medium",
			Rationale:   "Undocumented port forwards make security auditing difficult and may hide unauthorized access",
			Remediation: "Add descriptions to all port-forward rules in Firewall > NAT > Port Forward",
			Tags:        []string{"nat-security", "documentation", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-055",
			Title:       "Outbound NAT Control",
			Description: "Outbound NAT should use hybrid or advanced mode for explicit control",
			Category:    "NAT Security",
			Severity:    "medium",
			Rationale:   "Automatic outbound NAT creates implicit rules without administrator review",
			Remediation: "Switch to hybrid or advanced outbound NAT mode in Firewall > NAT > Outbound",
			Tags:        []string{"nat-security", "outbound-nat", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-056",
			Title:       "NAT Reflection Disabled",
			Description: "NAT reflection (hairpin NAT) should be disabled",
			Category:    "NAT Security",
			Severity:    "low",
			Rationale:   "NAT reflection complicates firewall rule auditing and can mask traffic sources",
			Remediation: "Disable NAT reflection in Firewall > Settings > Advanced",
			Tags:        []string{"nat-security", "nat-reflection", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-057",
			Title:       "UPnP/NAT-PMP Disabled",
			Description: "UPnP and NAT-PMP should be disabled to prevent automatic port mapping",
			Category:    "Service Hardening",
			Severity:    "high",
			Rationale:   "UPnP allows any internal host to create firewall holes without authorization",
			Remediation: "Disable UPnP and NAT-PMP in Services > UPnP/NAT-PMP",
			Tags:        []string{"service-hardening", "upnp", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-058",
			Title:       "DNSSEC Validation",
			Description: "DNSSEC validation should be enabled on the DNS resolver",
			Category:    "DNS Security",
			Severity:    "medium",
			Rationale:   "DNSSEC prevents DNS spoofing by cryptographically verifying DNS responses",
			Remediation: "Enable DNSSEC in Services > Unbound DNS > General",
			Tags:        []string{"dns-security", "dnssec", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-059",
			Title:       "DNS Resolver Access Restriction",
			Description: "DNS resolver should restrict access to specific interfaces",
			Category:    "DNS Security",
			Severity:    "medium",
			Rationale:   "Unrestricted DNS resolver access can be abused for DNS amplification attacks",
			Remediation: "Restrict Unbound DNS resolver to internal interfaces in Services > Unbound DNS > General",
			Tags:        []string{"dns-security", "access-restriction", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-060",
			Title:       "Configuration Revision Tracking",
			Description: "Configuration changes should be tracked with revision history",
			Category:    "Change Management",
			Severity:    "info",
			Rationale:   "Revision tracking enables rollback and audit trail for configuration changes",
			Remediation: "Enable configuration history in System > Configuration > History",
			Tags:        []string{"change-management", "revision-tracking", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-061",
			Title:       "HA Configuration",
			Description: "High availability should be fully configured when pfsync is in use",
			Category:    "High Availability",
			Severity:    "medium",
			Rationale:   "Incomplete HA configuration can lead to state synchronization failures and outages",
			Remediation: "Complete HA configuration in System > High Availability with pfsync peer and sync settings",
			Tags:        []string{"high-availability", "pfsync", "firewall-controls"},
		},

		// Configuration Inventory controls (FIREWALL-062 through -063)
		{
			ID:          "FIREWALL-062",
			Title:       "DHCP Scope Inventory",
			Description: "Reports configured DHCP scopes and their interfaces",
			Category:    "Configuration Inventory",
			Severity:    "info",
			Rationale:   "DHCP scope inventory enables configuration oversight and documentation",
			Remediation: "No action required — this is an informational observation",
			Tags:        []string{"inventory", "dhcp", "firewall-controls"},
		},
		{
			ID:          "FIREWALL-063",
			Title:       "Active Interface Summary",
			Description: "Reports enabled interfaces and their types",
			Category:    "Configuration Inventory",
			Severity:    "info",
			Rationale:   "Interface inventory enables network topology documentation",
			Remediation: "No action required — this is an informational observation",
			Tags:        []string{"inventory", "interfaces", "firewall-controls"},
		},
	}
}
