package converter

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/yuin/goldmark"
	emoji "github.com/yuin/goldmark-emoji"
	"github.com/yuin/goldmark/extension"
	goldmark_parser "github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer/html"
)

// htmlShell wraps rendered HTML body content in a self-contained HTML document
// with embedded CSS for offline viewing. No external resources are loaded.
// CSS values are inline rather than extracted as Go constants since the template
// is a single self-documenting unit (consistent with internal/diff/formatters/html.go).
const htmlShell = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>OPNsense Configuration Report</title>
<style>
:root {
  --bg: #fff; --text: #1a1a2e; --border: #e0e0e0;
  --bg-surface: #f8f9fa; --code-bg: #f4f4f4;
  --note: #0969da; --warning: #9a6700; --tip: #1a7f37;
  --caution: #cf222e; --important: #8250df;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #1a1a2e; --text: #e0e0e0; --border: #333;
    --bg-surface: #16213e; --code-bg: #1e1e2e;
    --note: #58a6ff; --warning: #d29922; --tip: #3fb950;
    --caution: #f85149; --important: #bc8cff;
  }
}
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  max-width: 960px; margin: 2rem auto; padding: 0 1rem;
  background: var(--bg); color: var(--text); line-height: 1.6; }
h1, h2, h3 { border-bottom: 1px solid var(--border); padding-bottom: 0.3em; }
h4, h5, h6 { margin-top: 1.5em; }
table { border-collapse: collapse; width: 100%%; margin: 1em 0; }
th, td { border: 1px solid var(--border); padding: 0.5em 0.75em; text-align: left; }
th { background: var(--bg-surface); font-weight: 600; }
code { background: var(--code-bg); padding: 0.15em 0.3em; border-radius: 3px; font-size: 0.9em; }
pre { background: var(--code-bg); padding: 1em; border-radius: 6px; overflow-x: auto; }
pre code { background: none; padding: 0; }
details { margin: 0.5em 0; }
summary { cursor: pointer; font-weight: 600; }
ul, ol { padding-left: 1.5em; }
li { margin: 0.25em 0; }
blockquote { border-left: 4px solid var(--border); margin: 1em 0; padding: 0.5em 1em;
  background: var(--bg-surface); }
.alert { border-left: 4px solid; margin: 1em 0; padding: 0.5em 1em; border-radius: 4px; }
.alert-title { font-weight: 700; margin: 0 0 0.25em 0; }
.alert-note { border-color: var(--note); background: rgba(9, 105, 218, 0.08); }
.alert-note .alert-title { color: var(--note); }
.alert-warning { border-color: var(--warning); background: rgba(154, 103, 0, 0.08); }
.alert-warning .alert-title { color: var(--warning); }
.alert-tip { border-color: var(--tip); background: rgba(26, 127, 55, 0.08); }
.alert-tip .alert-title { color: var(--tip); }
.alert-caution { border-color: var(--caution); background: rgba(207, 34, 46, 0.08); }
.alert-caution .alert-title { color: var(--caution); }
.alert-important { border-color: var(--important); background: rgba(130, 80, 223, 0.08); }
.alert-important .alert-title { color: var(--important); }
@media (prefers-color-scheme: dark) {
  .alert-note { background: rgba(88, 166, 255, 0.1); }
  .alert-warning { background: rgba(210, 153, 34, 0.1); }
  .alert-tip { background: rgba(63, 185, 80, 0.1); }
  .alert-caution { background: rgba(248, 81, 73, 0.1); }
  .alert-important { background: rgba(188, 140, 255, 0.1); }
}
@media print { body { max-width: 100%%; margin: 0; } }
</style>
</head>
<body>
%s
<footer style="margin-top:2rem; padding-top:1rem; border-top:1px solid var(--border); font-size:0.85em; color:#888;">
Generated by opnDossier
</footer>
</body>
</html>
`

// reAlertBlockquote matches goldmark's HTML output for GitHub-style alert blockquotes.
// Goldmark renders `> [!TYPE]\n> content` as:
//
//	<blockquote>\n<p>[!TYPE]<br />\ncontent</p>\n</blockquote>
//
// This regex captures the alert type (NOTE, WARNING, etc.) and body content.
var reAlertBlockquote = regexp.MustCompile(
	`(?s)<blockquote>\s*<p>\[!(NOTE|WARNING|TIP|CAUTION|IMPORTANT)\]` +
		`(?:<br\s*/?>)?\s*\n?(.*?)</p>\s*</blockquote>`,
)

// alertSubmatchLen is the minimum submatch length for alert regex matches
// (full match + alert type + body content).
const alertSubmatchLen = 3

// alertTitles maps alert type identifiers to their display titles.
var alertTitles = map[string]string{
	"NOTE":      "Note",
	"WARNING":   "Warning",
	"TIP":       "Tip",
	"CAUTION":   "Caution",
	"IMPORTANT": "Important",
}

// htmlOutputRenderer renders the markdown report into the HTML document a user
// opens in a browser (RenderMarkdownToHTML).
//
// Raw HTML passthrough is deliberately NOT enabled. This renderer previously set
// html.WithUnsafe() on the argument that config-derived values reach markdown
// only through text-producing methods, which goldmark escapes. That does not
// hold: goldmark decides text node vs raw-HTML node during parsing, before any
// escaping, so `<img src=x onerror=...>` in a hostname parses as raw HTML and
// passes through verbatim.
//
// Together with the escaping in formatters.EscapeMarkdownValue this is the
// second layer. Nothing the converter emits contains intentional raw HTML.
var htmlOutputRenderer = goldmark.New(
	goldmark.WithExtensions(extension.Table),
	goldmark.WithParserOptions(
		goldmark_parser.WithAutoHeadingID(),
	),
	goldmark.WithRendererOptions(
		html.WithHardWraps(),
		html.WithXHTML(),
	),
)

// goldmarkRenderer backs plain text output (StripMarkdownFormatting), where
// HTML is only an intermediate step before html2text discards the markup.
//
// It keeps html.WithUnsafe(): that intermediate HTML never reaches a browser,
// and dropping it would change plaintext output, since goldmark would replace
// the element with a comment and html2text would discard the text inside it.
var goldmarkRenderer = goldmark.New(
	goldmark.WithExtensions(extension.Table),
	goldmark.WithParserOptions(
		goldmark_parser.WithAutoHeadingID(),
	),
	goldmark.WithRendererOptions(
		html.WithHardWraps(),
		html.WithXHTML(),
		html.WithUnsafe(), // intermediate HTML only; html2text strips it immediately
	),
)

// transformAlertBlockquotes converts goldmark blockquote output containing
// GitHub-style alert markers ([!NOTE], [!WARNING], etc.) into styled HTML
// div elements. Non-alert blockquotes are left unchanged.
func transformAlertBlockquotes(htmlContent string) string {
	return reAlertBlockquote.ReplaceAllStringFunc(htmlContent, func(match string) string {
		submatch := reAlertBlockquote.FindStringSubmatch(match)
		if len(submatch) < alertSubmatchLen {
			return match
		}

		alertType := submatch[1]
		body := strings.TrimSpace(submatch[2])
		typeLower := strings.ToLower(alertType)

		title, ok := alertTitles[alertType]
		if !ok {
			return match
		}

		return fmt.Sprintf(
			"<div class=\"alert alert-%s\">\n<p class=\"alert-title\">%s</p>\n<p>%s</p>\n</div>",
			typeLower, title, body,
		)
	})
}

// RenderMarkdownToHTML converts markdown content to a self-contained HTML document.
// It uses goldmark for markdown-to-HTML conversion, transforms GitHub-style alert
// blockquotes into styled div elements, and wraps the result in htmlShell.
func RenderMarkdownToHTML(md string) (string, error) {
	var buf strings.Builder
	if err := htmlOutputRenderer.Convert([]byte(md), &buf); err != nil {
		return "", fmt.Errorf("failed to convert markdown to HTML: %w", err)
	}

	body := transformAlertBlockquotes(buf.String())

	return fmt.Sprintf(htmlShell, body), nil
}

// richGoldmarkRenderer is a goldmark instance configured with extended markdown
// features (GFM, definition lists, emoji, footnotes) for rendering markdown
// content to HTML. Used by RenderMarkdown and ValidateMarkdown.
//
// This one keeps html.WithUnsafe() because its only production consumer,
// internal/diff/formatters, writes literal <details>/<summary> wrappers that
// must survive rendering. That makes the diff formatter, not this renderer,
// responsible for keeping config-derived values inert. Anything added there
// which writes a configuration value must escape it or wrap it in a code span;
// passthrough is on here and will not catch the mistake.
var richGoldmarkRenderer = goldmark.New(
	goldmark.WithExtensions(extension.GFM, extension.DefinitionList, emoji.Emoji, extension.Footnote),
	goldmark.WithParserOptions(
		goldmark_parser.WithAutoHeadingID(),
	),
	goldmark.WithRendererOptions(
		html.WithHardWraps(),
		html.WithXHTML(),
		html.WithUnsafe(),
	),
)

// RenderMarkdown parses and renders markdown content to HTML using goldmark
// with extended features (GFM, definition lists, emoji, footnotes).
// Returns the rendered HTML string or an error if rendering fails.
// Raw HTML tags (e.g., <details>, <summary>) are preserved in the output.
func RenderMarkdown(content string) (string, error) {
	var buf strings.Builder
	if err := richGoldmarkRenderer.Convert([]byte(content), &buf); err != nil {
		return "", fmt.Errorf("failed to render markdown: %w", err)
	}

	return buf.String(), nil
}

// ValidateMarkdown checks if the provided markdown content is syntactically valid.
// It returns an error if the content cannot be parsed as markdown.
func ValidateMarkdown(content string) error {
	var buf strings.Builder
	if err := richGoldmarkRenderer.Convert([]byte(content), &buf); err != nil {
		return fmt.Errorf("failed to parse markdown content: %w", err)
	}

	return nil
}
