package cmd

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestDocsCmdGeneratesHeadlineCommandPages exercises runGenerateMarkdownDocs
// against a throwaway output directory and asserts that each headline command
// produced a non-empty markdown page containing its Cobra Short/Example text.
// This keeps the CLI reference tied to the real command tree so a regression
// (a removed command, an emptied Long, a stripped Example) fails CI.
func TestDocsCmdGeneratesHeadlineCommandPages(t *testing.T) {
	// Do NOT use t.Parallel() — cmd package uses package-level flag globals.
	// See GOTCHAS §1.1.
	outputDir := t.TempDir()

	// Use a disposable cobra.Command whose Root() resolves to rootCmd so that
	// GenMarkdownTreeCustom walks the real command tree.
	tmp := &cobra.Command{Use: "tmp"}
	rootCmd.AddCommand(tmp)
	t.Cleanup(func() { rootCmd.RemoveCommand(tmp) })

	require.NoError(t, runGenerateMarkdownDocs(tmp, []string{outputDir}))

	// Every headline command must produce a markdown file under outputDir.
	for _, name := range []string{
		"opndossier.md",
		"opndossier_audit.md",
		"opndossier_convert.md",
		"opndossier_display.md",
		"opndossier_diff.md",
		"opndossier_sanitize.md",
		"opndossier_validate.md",
	} {
		path := filepath.Join(outputDir, name)
		stat, err := os.Stat(path)
		require.NoErrorf(t, err, "expected generated page %s", name)
		assert.Positivef(t, stat.Size(), "page %s should be non-empty", name)
	}

	// Spot-check that the audit page contains content lifted from Cobra metadata.
	auditPath := filepath.Join(outputDir, "opndossier_audit.md")
	body, err := os.ReadFile(auditPath)
	require.NoError(t, err)
	assert.Contains(t, string(body), "Run security audit and compliance checks",
		"generated audit page should include the Cobra Short text")
	assert.Contains(t, string(body), "opndossier audit config.xml",
		"generated audit page should include Example invocations")
	assert.Contains(t, string(body), "Auto-generated by 'opndossier docs'",
		"generated pages should carry the authoring banner")
}

// TestDocsCmdIsHidden protects the UX decision to keep the docs command out of
// the default help output. If someone intentionally un-hides it, update this
// test and AGENTS.md together.
func TestDocsCmdIsHidden(t *testing.T) {
	assert.True(t, docsCmd.Hidden, "docs command must remain hidden — it is an authoring tool")
}
